Update: support rewrite "gcpt restore" manual
OpenXiangShan/difftest pull request #157
Opened 2023-09-18 10:30 UTC by xyyy1420

2023-09-19 07:03 UTC, shinezyy requested changes
overwrite_nbytes should not use 'o' as shorthand, because o is usually used for output or some common options.

please remove 'o' from L161, L172, and L263

2023-09-19 07:03 UTC, shinezyy commented on src/test/csrc/verilator/emu.cpp
overwrite_nbytes` should not use 'o' as shorthand

2023-09-21 01:55 UTC, shinezyy submitted a review, later dismissed
seems Ok

2023-09-21 08:29 UTC, poemonsense submitted a review, later dismissed

2023-09-21 08:29 UTC, poemonsense commented on src/test/csrc/verilator/emu.cpp
> +  printf("      --overwrite-nbytes=n   set valid bytes,but less than 0xf00,default value is 0x700\n");
The default value here is different from the value in `uint64_t overwrite_nbytes = 0xe00;`? 

Better to use `default: 0xe00` to reduce the length of the message and add a whitespace after `,`

2023-09-22 01:31 UTC, poemonsense commented on src/test/csrc/verilator/emu.cpp
> +    InputReader *reader=new FileReader(args.gcpt_restore);
and a whitespace after `,`

2023-09-22 02:13 UTC, merged