Add paladin runs checkpoint in batches
OpenXiangShan/difftest pull request #264
Opened 2024-01-22 08:09 UTC by xiaokamikami

增加帕拉丁批量运行checkpoint并导出IPC的功能

2024-01-22 09:03 UTC, poemonsense requested changes
1) use English for commit messages

2) separate different changes to different PRs

3) remove debug prints and other unnecessary code

2024-01-22 09:23 UTC, xiaokamikami commented
> 1. use English for commit messages
> 2. separate different changes to different PRs
> 3. remove debug prints and other unnecessary code

All these commits add up to do this, so can we not split them

2024-01-22 10:50 UTC, poemonsense commented on src/test/csrc/difftest/difftest.cpp
> +      printf("inst count %ld", difftest_commit_sum(i));
what's this?

2024-01-22 10:50 UTC, poemonsense commented on src/test/csrc/difftest/difftest.cpp
> +  printf("instr countsum : %ld\n", get_instr_sum());
what's this?

2024-01-22 10:52 UTC, poemonsense commented on src/test/csrc/common/ram.cpp
> +    if (gcpt_bin != nullptr) {
this is not related to palladium at all

2024-01-22 10:53 UTC, poemonsense commented on src/test/csrc/checkpoint/xs_MemRam.h
> +class xs_MemRam
why do we need this? we already have checkpoints support in ram.cpp

2024-01-22 10:53 UTC, poemonsense commented on src/test/csrc/difftest/difftest.h
> +    retire_instr_cntsum += count;
this is not related to palladium at all

2024-01-22 10:53 UTC, poemonsense commented on src/replace/checkpoint/MemRWHelper.v
> +// The memory used to load the checkpoint
why do we need another MemRWHelper here? Why don't you add it to chisel?

2024-01-22 10:54 UTC, poemonsense commented on src/test/csrc/checkpoint/run_checkpoint.sh
> +RESULT_PATH="/nfs/home/fengkehan/checkpoint-result"
what's this?

2024-01-22 10:54 UTC, poemonsense commented on src/test/csrc/checkpoint/run_checkpoint.sh
> +    prefix=${var%%.*}  # 获取第一个点号（.）之前的部分
why is there Chinese?

2024-01-22 10:54 UTC, poemonsense requested changes
Please be serious about what I commented before.

2024-01-23 02:04 UTC, xiaokamikami commented on src/test/csrc/common/ram.cpp
> +    if (gcpt_bin != nullptr) {
When Paladin loads a checkpoint, you need to use gcpt.bin to override the restore section

2024-01-23 02:06 UTC, xiaokamikami commented on src/test/csrc/checkpoint/xs_MemRam.h
> +class xs_MemRam
This ram is used to initialize the MemRWHelper load gz, initialized with DPIC but not accessed with DPIC

2024-01-23 02:07 UTC, xiaokamikami commented on src/test/csrc/difftest/difftest.cpp
> +      printf("inst count %ld", difftest_commit_sum(i));
modified

2024-01-23 02:08 UTC, xiaokamikami commented on src/test/csrc/difftest/difftest.cpp
> +  printf("instr countsum : %ld\n", get_instr_sum());
The code is removed

2024-01-23 02:08 UTC, xiaokamikami commented on src/replace/checkpoint/MemRWHelper.v
> +// The memory used to load the checkpoint
This MemRWHelper supports larger memory for loading checkpoint, I'm using this version since I can't chisel yet

2024-01-23 02:09 UTC, xiaokamikami commented on src/test/csrc/checkpoint/run_checkpoint.sh
> +RESULT_PATH="/nfs/home/fengkehan/checkpoint-result"
Fixed

2024-01-23 02:09 UTC, xiaokamikami commented on src/test/csrc/checkpoint/run_checkpoint.sh
> +    prefix=${var%%.*}  # 获取第一个点号（.）之前的部分
Fixed

2024-01-23 02:10 UTC, xiaokamikami commented on src/test/csrc/difftest/difftest.h
> +    retire_instr_cntsum += count;
The use of this variable is required to derive the IPC at the end of the simulation at Paladin

2024-01-23 03:15 UTC, poemonsense commented
1) #157 adds support for overriding the checkpoint restorer. But this PR seems to add it again with duplicated functions. Firstly, you have to read their code and see whether your code and their code can be reused. Secondly, this feature is not related to palladium. If you need to modify the related C++ code, do it separately in another PR. Third, ram definitions should be in ram.cpp and ram.h only. I don't understand why you need a separated `csrc/checkpoint` directory. I don't see any necessity for these files.

2) If you are going to add support for the instruction count when difftest is not connected via DPI-C, do it separately in another PR. This feature is also not related to palladium.

3) Similarly, if you are adding arguments to the VCS top, do it separately in another PR because this is not palladium specific.

4) Duplicated code in `checkpoint` directory is not accepted. This is an open-source project, not a homework. You have to learn it and do it the correct way. Running the code correctly with the correct output does not mean that you are doing it in the correct way. If you don't know Chisel and refuse to implement it in Chisel, stop spending time on this and @klin02 may have free time to do it.

2024-01-23 03:42 UTC, xiaokamikami commented
> 1. [Support overwriting the gcpt restorer manually #157](https://github.com/OpenXiangShan/difftest/pull/157) adds support for overriding the checkpoint restorer. But this PR seems to add it again with duplicated functions. Firstly, you have to read their code and see whether your code and their code can be reused. Secondly, this feature is not related to palladium. If you need to modify the related C++ code, do it separately in another PR. Third, ram definitions should be in ram.cpp and ram.h only. I don't understand why you need a separated `csrc/checkpoint` directory. I don't see any necessity for these files.
> 2. If you are going to add support for the instruction count when difftest is not connected via DPI-C, do it separately in another PR. This feature is also not related to palladium.
> 3. Similarly, if you are adding arguments to the VCS top, do it separately in another PR because this is not palladium specific.
> 4. Duplicated code in `checkpoint` directory is not accepted. This is an open-source project, not a homework. You have to learn it and do it the correct way. Running the code correctly with the correct output does not mean that you are doing it in the correct way. If you don't know Chisel and refuse to implement it in Chisel, stop spending time on this and @klin02 may have free time to do it.

The code in csrc/checkpoint is used to help Verilog memory initialize the GZ file.I'm learning chisel, so I'll resubmit the pr later
csrc/checkpoint中的代码用于帮助Verilog memory初始化GZ文件，我正在学习chisel，后面再重新提交pr吧

2024-01-23 03:42 UTC, closed without merging