vcs: add support for --max-instrs option
OpenXiangShan/difftest pull request #290
Opened 2024-02-19 08:03 UTC by xiaokamikami

Add a per-instruction counter to exit, primarily for checkpoint testing

2024-02-20 06:25 UTC, poemonsense reviewed
let @klin02 have a review and test

2024-02-20 06:25 UTC, poemonsense commented on src/test/csrc/difftest/difftest.cpp
> +  {
Follow the same code style as existing code (to put `{` at the same line of `for`)

2024-02-20 06:41 UTC, xiaokamikami commented on src/test/csrc/difftest/difftest.cpp
> +  {
OK

2024-02-20 09:47 UTC, klin02 commented on src/test/csrc/vcs/vcs_main.cpp
> +extern "C" void set_max_instrs(long mc) {
It seems type `long` mismatchs DPI-C declare? Better use same type and more clear name then `mc`~

2024-02-20 09:58 UTC, klin02 commented
Better add exit Info like https://github.com/OpenXiangShan/difftest/blob/0330732fcdd22c7209866a3ae2213c8b29a4605b/src/test/vsrc/vcs/top.v#L199

2024-02-20 10:10 UTC, klin02 commented on src/test/csrc/difftest/difftest.cpp
> +void difftest_commit_clean() {
When will difftest_commit_clean be used? 
By the way, better use same code style as other difftest_xxx Func.
for (int i = 0; i < NUM_CORES; i++) ...

Same for other new function.

2024-02-20 10:27 UTC, klin02 commented
Does retire_instr_cntsum have any use other than controlling instruction overflow exit? Can trap->instrcnt be used as same role like emu?
https://github.com/OpenXiangShan/difftest/blob/0330732fcdd22c7209866a3ae2213c8b29a4605b/src/test/csrc/verilator/emu.cpp#L698
If some unused function is necessary for checkpoint. Maybe you can explain it in this PR?

2024-02-21 03:10 UTC, klin02 requested changes

2024-02-21 03:10 UTC, klin02 commented on src/test/csrc/vcs/vcs_main.cpp
> +static int max_instrs = 0;
use uint64_t? Line 47 arg is uint64_t, and trap->instrCnt is also uint64_t

2024-02-21 03:10 UTC, klin02 commented on src/test/csrc/vcs/vcs_main.cpp
> +      eprintf(ANSI_COLOR_GREEN "checkpoint reach the operating limit exit\n" ANSI_COLOR_RESET);
Seems --max-instrs is independent to checkpoint. Simply `EXCEEDED MAX INSTR: %d` is enough

2024-02-21 06:59 UTC, poemonsense commented
In Linux, the return code of a process indicates the state of the process. See https://www.agileconnection.com/article/overview-linux-exit-codes

Return code 0 means the program exits normally. For max-instrs, the simulation should return 0 as well. This is also the normal behavior in the Verilator simulation as shown in https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/common/main.cpp#L45 and https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/verilator/emu.h#L138

Please do not use 0xff as the return code

2024-02-21 07:06 UTC, xiaokamikami commented
> In Linux, the return code of a process indicates the state of the process. See https://www.agileconnection.com/article/overview-linux-exit-codes
> 
> Return code 0 means the program exits normally. For max-instrs, the simulation should return 0 as well. This is also the normal behavior in the Verilator simulation as shown in https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/common/main.cpp#L45 and https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/verilator/emu.h#L138
> 
> Please do not use 0xff as the return code

In the next version I need to determine if it's max-instrs and run a separate handler

2024-02-21 07:10 UTC, poemonsense commented
> > In Linux, the return code of a process indicates the state of the process. See https://www.agileconnection.com/article/overview-linux-exit-codes
> > Return code 0 means the program exits normally. For max-instrs, the simulation should return 0 as well. This is also the normal behavior in the Verilator simulation as shown in https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/common/main.cpp#L45 and https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/verilator/emu.h#L138
> > Please do not use 0xff as the return code
> 
> In the next version I need to determine if it's max-instrs and run a separate handler

OK. It's only for internal usage

2024-02-21 07:26 UTC, xiaokamikami commented on src/test/csrc/vcs/vcs_main.cpp
> +      eprintf(ANSI_COLOR_GREEN "checkpoint reach the operating limit exit\n" ANSI_COLOR_RESET);
fix

2024-02-21 07:26 UTC, xiaokamikami commented on src/test/csrc/vcs/vcs_main.cpp
> +static int max_instrs = 0;
fix

2024-02-21 08:11 UTC, klin02 approved these changes

2024-02-21 08:23 UTC, merged