verilator.mk: Add support for PGO
OpenXiangShan/difftest pull request #392
Opened 2024-06-07 10:24 UTC by cyyself

This commit add PGO_CFLAGS and PGO_LDFLAGS when calling verilator to generate Makefile. And add script to build PGO for both GCC and LLVM.

Example usage:

apply this patch to XiangShan Makefile:

```diff
diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -205,7 +205,7 @@ idea:

 # verilator simulation
 emu: sim-verilog
-       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES)
+       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES) PGO_WORKLOAD=`realpath $(PGO_WORKLOAD) 2>/dev/null` LLVM_PROFDATA=$(LLVM_PROFDATA)

 # vcs simulation
 simv: sim-verilog
```

Then, build emu with PGO support with LLVM:
```shell
make emu MFC=1 EMU_THREADS=16 NUM_CORES=1 PGO_WORKLOAD=ready-to-run/coremark-2-iteration.bin LLVM_PROFDATA=llvm-profdata -j `nproc`
```

If the compiler of verilator is GCC, we should not use LLVM_PROFDATA:
```shell
make emu MFC=1 EMU_THREADS=16 NUM_CORES=1 PGO_WORKLOAD=ready-to-run/coremark-2-iteration.bin -j `nproc`
```

2024-06-07 14:20 UTC, poemonsense reviewed
The PGO commands look good to me except for some minor changes.

I'm suggesting adding a CI test for verify the PGO process. NutShell builds quickly. I'm assuming $(MAKE) will have all variables including PGO_WORKLOAD. That to say, if you `make emu PGO_WORKLOAD=../ready-to-run/microbench.bin` would work perfectly (given the relative path starting at `difftest` is correctly pointing to a file).

2024-06-07 14:20 UTC, poemonsense commented on verilator.mk
> +EMU_PGO_DIR  = $(BUILD_DIR)/pgo
What about emu-compile-pgo? We are using `emu-compile` for verilator, `simv-compile` for VCS, and `pldm-compile` for Palladium.

2024-06-07 14:20 UTC, poemonsense commented on verilator.mk
> +  -CFLAGS "\$$(PGO_CFLAGS)"         \
Will this CLAGS be appended to the original CFLAGS at line 113? I'm only asking to ensure it has been tested.

2024-06-07 14:20 UTC, poemonsense commented on verilator.mk
> +	$(EMU) -i $(PGO_WORKLOAD) --max-cycles=$(PGO_MAX_CYCLE) 1>$(EMU_PGO_DIR)/`date +%s`.log 2>$(EMU_PGO_DIR)/`date +%s`.err
I noticed you have provided the patch for XiangShan which contains a realpath for PGO_WORKLOAD.

I'm considering adding a checker in this Makefile as well to ensure the user is passing an existed filename to PGO_WORKLOAD. Since XiangShan's Makefile is out of the control of DiffTest, we need to ensure the users of difftest passing a correct path of PGO_WORKLOAD at make-time. This implies that, as long as the user passes a legal file path (either realpath or not) with PGO_WORKLOAD, DiffTest accepts it. With this checker, external users (outside XiangShan) can connect DiffTest correctly with warnings in appropriate cases.

2024-06-07 14:23 UTC, cyyself commented on verilator.mk
> +  -CFLAGS "\$$(PGO_CFLAGS)"         \
> Will this CLAGS be appended to the original CFLAGS at line 113? I'm only asking to ensure it has been tested.

Yes. I have tested it.

2024-06-07 14:23 UTC, poemonsense commented
> ```diff
> diff --git a/Makefile b/Makefile
> --- a/Makefile
> +++ b/Makefile
> @@ -205,7 +205,7 @@ idea:
> 
>  # verilator simulation
>  emu: sim-verilog
> -       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES)
> +       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES) PGO_WORKLOAD=`realpath $(PGO_WORKLOAD) 2>/dev/null`
> 
>  # vcs simulation
>  simv: sim-verilog
> ```

Is it better to move this realpath to separate lines in Makefile?

```
ifneq ($(PGO_WORKLOAD),)
// update PGO_WORLOAD here with realpath
endif
```

Do we really need to pass the PGO_WORKLOAD explicitly? I'm assuming all variables are perserved by $(MAKE)

2024-06-08 01:29 UTC, poemonsense commented on verilator.mk
> +  -CFLAGS "\$$(PGO_CFLAGS)"         \
I just noticed line 113 is "$(EMU_CXXFLAGS)" and line 115 is "\$$(PGO_CFLAGS)"

Are `$` and `\$$` same?

2024-06-08 02:25 UTC, eastonman requested changes

2024-06-08 02:25 UTC, eastonman commented on verilator.mk
> +	@echo "If your varilator is compiled with LLVM, please don't forget"
a typo here for verilator

2024-06-08 02:25 UTC, eastonman commented on verilator.mk
> +	@echo "If your varilator is compiled with GCC, please ignore this"
here too

2024-06-08 02:28 UTC, eastonman commented
Do you have some simulation performance stats you can share?
And how much time does max-cycle 2M take on an ordinary EPYC 2nd or 3rd gen machine?

2024-06-10 15:48 UTC, cyyself commented on verilator.mk
> +  -CFLAGS "\$$(PGO_CFLAGS)"         \
No.

1.`$$` is used in Makefile to produce `$`: https://www.gnu.org/software/make/manual/html_node/Variables-in-Recipes.html
2. Then, `\$` is used in the shell to pass the string rather than the variable name.

2024-06-10 15:49 UTC, cyyself commented on verilator.mk
> +EMU_PGO_DIR  = $(BUILD_DIR)/pgo
That sounds like a good idea. I will fix it tomorrow.

2024-06-10 15:50 UTC, cyyself commented
> > ```diff
> > diff --git a/Makefile b/Makefile
> > --- a/Makefile
> > +++ b/Makefile
> > @@ -205,7 +205,7 @@ idea:
> > 
> >  # verilator simulation
> >  emu: sim-verilog
> > -       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES)
> > +       $(MAKE) -C ./difftest emu SIM_TOP=SimTop DESIGN_DIR=$(NOOP_HOME) NUM_CORES=$(NUM_CORES) PGO_WORKLOAD=`realpath $(PGO_WORKLOAD) 2>/dev/null`
> > 
> >  # vcs simulation
> >  simv: sim-verilog
> > ```
> 
> Is it better to move this realpath to separate lines in Makefile?
> 
> ```
> ifneq ($(PGO_WORKLOAD),)
> // update PGO_WORLOAD here with realpath
> endif
> ```
> 
> Do we really need to pass the PGO_WORKLOAD explicitly? I'm assuming all variables are perserved by $(MAKE)

It's just for adding the real path and passed to another Makefile.

2024-06-10 15:55 UTC, cyyself commented
> Do you have some simulation performance stats you can share? And how much time does max-cycle 2M take on an ordinary EPYC 2nd or 3rd gen machine?

I haven't tested it on the AMD EPYC Server. On my 13900k machine with 16 threads, with coremark trained PGO and coremark emu benchmark, it gets about 2x faster, which finished the 2 iter coremark in 46s, original emu takes about 120s. This result is about 1x faster than non-PGO emu on 7950X3D, which takes 76s to finish 2 iter coremark. However, I think we may need a better workload as a training workload that uses MMU and RVV.

2024-06-11 03:11 UTC, cyyself commented on verilator.mk
> +EMU_PGO_DIR  = $(BUILD_DIR)/pgo
> What about emu-compile-pgo? We are using `emu-compile` for verilator, `simv-compile` for VCS, and `pldm-compile` for Palladium.

After thinking for a while, I think keeping `emu-compile` might be better. Since the C compiler does the PGO, the C code generated by the verilator can be reused. Also, compiling Verilog to C takes time on a single thread, but compiling C code to binary is very fast. This will also reduce users' switching time from normal emu to PGO emu.

2024-06-11 03:58 UTC, cyyself commented on verilator.mk
> +	$(EMU) -i $(PGO_WORKLOAD) --max-cycles=$(PGO_MAX_CYCLE) 1>$(EMU_PGO_DIR)/`date +%s`.log 2>$(EMU_PGO_DIR)/`date +%s`.err
I have added `stat` in line 149, and I think a checker like this is OK.

2024-06-11 09:35 UTC, poemonsense commented on verilator.mk
> +  -CFLAGS "\$$(PGO_CFLAGS)"         \
I see

2024-06-11 09:38 UTC, poemonsense commented on verilator.mk
> +EMU_PGO_DIR  = $(BUILD_DIR)/pgo
`BUILD_DIR` is `build`. `EMU_DIR` is `build/emu-compile`.

I suggest using `build/emu-compile-pgo` for `EMU_PGO_DIR` instead of `build/pgo`. You may also use `EMU_DIR/pgo`.

2024-06-11 09:42 UTC, poemonsense commented
> The PGO commands look good to me except for some minor changes.
> 
> I'm suggesting adding a CI test for verify the PGO process. NutShell builds quickly. I'm assuming $(MAKE) will have all variables including PGO_WORKLOAD. That to say, if you `make emu PGO_WORKLOAD=../ready-to-run/microbench.bin` would work perfectly (given the relative path starting at `difftest` is correctly pointing to a file).


There are two unresolved comments

1) It's better to add a CI test.

2) Better to use `build/emu-compile-pgo` or `build/emu-compile/pgo` instead of `build/pgo` which confuses the user.

2024-06-11 09:48 UTC, cyyself commented on verilator.mk
> +EMU_PGO_DIR  = $(BUILD_DIR)/pgo
OK. Solved.

2024-06-11 13:00 UTC, poemonsense submitted a review, later dismissed
Approving it now.

Please let me know when it's ready for merging. CI may be added in later PRs.

2024-06-11 13:01 UTC, poemonsense commented on verilator.mk
> +	@echo "Trainning emu with PGO Workload..."
Typo: training

2024-06-11 13:04 UTC, poemonsense commented on verilator.mk
> +EMU_PGO_DIR  = $(EMU_DIR)/pgo
I noticed $(EMU_DIR) is defined in line 91. Do we need to move this line after line 91?

2024-06-11 16:48 UTC, cyyself commented on verilator.mk
> +EMU_PGO_DIR  = $(EMU_DIR)/pgo
Oh. It's my fault. Fixed.

2024-06-11 16:55 UTC, cyyself commented
Maybe I should add a CI based on NutShell. But I'm not sure I have time to do that recently. I'm figuring out the problem caused by a recent update on the XiangShan master branch, which can not finish C compile with -fprofile-generate and O3 or -Os on llvm-18 in 30 minutes, which makes PGO unusable. But with -O0, there is a lot of performance degradation.

2024-06-12 03:26 UTC, poemonsense commented
> Maybe I should add a CI based on NutShell. But I'm not sure I have time to do that recently. I'm figuring out the problem caused by a recent update on the XiangShan master branch, which can not finish C compile with -fprofile-generate and (O3 or -Os) on llvm-18 in 30 minutes, which makes PGO unusable. But with -O0, there is a lot of performance degradation.

We can leave this PR unmerged until these issues fixed.

2024-06-13 03:26 UTC, cyyself commented
> It's a very good work. Thanks for the contribution. There are two unresolved comments
> 
> 1. It's better to add a CI test.

CI added now.

> 2. Better to use `build/emu-compile-pgo` or `build/emu-compile/pgo` instead of `build/pgo` which confuses the user.

I use `build/emu-compile/pgo` now.

2024-06-13 03:28 UTC, cyyself commented
And please don't merge in squash mode; I have some important messages in each commit message.

2024-06-13 04:30 UTC, cyyself commented
> > Maybe I should add a CI based on NutShell. But I'm not sure I have time to do that recently. I'm figuring out the problem caused by a recent update on the XiangShan master branch, which can not finish C compile with -fprofile-generate and (O3 or -Os) on llvm-18 in 30 minutes, which makes PGO unusable. But with -O0, there is a lot of performance degradation.
> 
> We can leave this PR unmerged until these issues fixed.

I think we can merge it first and then add a parameter in Makefile to switch the optimization level for difftest without rerunning the verilator. Now clang-18 is broken on the verilator-generated XiangShan RTL. So I can’t provide a fair comparison with different optimization levels. But one thing I can tell is the instruction count on 8 threads coremark is nearly the same on GCC-14 -O3 and LLVM-18 -O3. But if we switched to -O1 on GCC-14, the instruction count on GCC-14 would be 3x compared to -O3. So providing a switch might be a good choice if we ran into a compile-time issue or emu performance issue.

2024-06-13 05:13 UTC, poemonsense approved these changes

2024-06-13 05:14 UTC, merged