difftest: gcpt supports automatic oversize in newer versions
OpenXiangShan/difftest pull request #460
Opened 2024-09-05 07:15 UTC by xiaokamikami

New versions of gcpt allow you to set oversize automatically. if you don't specify size manually, gcpt will look for an oversize flag

2024-09-05 08:04 UTC, poemonsense approved these changes
I think mixing in the dirty code for checkpoints is a bad idea. I suggest rethinking how the support for checkpoints should be implemented.

However, I'm ok to approve it if you can rearrange the multiple printf's. I don't understand why you need so many printf's

2024-09-05 08:04 UTC, poemonsense commented on src/test/csrc/vcs/vcs_main.cpp
> +    printf("gcpt auto overwrite size :%x\n", overwrite_nbytes);
Format the printf please. "size: " instead of "size :"

2024-09-05 14:30 UTC, poemonsense requested changes
Why is the PR titled coverage?

2024-09-06 03:00 UTC, xiaokamikami commented
> I think mixing in the dirty code for checkpoints is a bad idea. I suggest rethinking how the support for checkpoints should be implemented.
> 
> However, I'm ok to approve it if you can rearrange the multiple printf's. I don't understand why you need so many printf's



> I think mixing in the dirty code for checkpoints is a bad idea. I suggest rethinking how the support for checkpoints should be implemented.
> 
> However, I'm ok to approve it if you can rearrange the multiple printf's. I don't understand why you need so many printf's

I have the code to print gcpt siz elsewhere, so I'm going to remove the printf here

2024-09-06 10:39 UTC, xiaokamikami commented
> Look good to me now.
> 
> Only VCS supports this? Do we need to add support for verilator?

I've also added support in case someone needs to run a new checkpoint on emu

2024-09-06 10:43 UTC, poemonsense commented on src/test/csrc/vcs/vcs_main.cpp
> +static bool overwrite_auto = false;
This bool seems useless?

2024-09-06 10:43 UTC, poemonsense commented on src/test/csrc/verilator/emu.cpp
> +         
Should indent using 2 spaces instead of 4 spaces. Also delete this empty line please

2024-09-06 10:44 UTC, poemonsense submitted a review, later dismissed

2024-09-06 12:41 UTC, poemonsense approved these changes
Thank you for the great work

2024-09-06 12:42 UTC, merged